export const TIMESTAMP_FORMAT = 'YYYY-MM-DD HH:mm:ss.SSS';

export const TIMESTAMP_FORMAT_YYYY_MM_DD_HH_mm_ss = 'YYYY-MM-DD HH:mm:ss';
export const TIMESTAMP_FORMAT_YYYY_MM_DD_HH_MM_SS_TRIMMED =
  'YYYY_MM_DD_HH_mm_ss';

export const DATE_FORMAT_YYYY_MM_DD = 'YYYY-MM-DD';

export const KYC_VALIDITY_IN_HRS = 24;

export const REPRESENTATION_DATE_FORMAT = 'YYYY-MM-DD';