export enum MANDATE_TYPE {
  ENACH = 'ENACH',
  UPI = 'UPI',
}

export enum MANDATE_STATUS {
  INITIATED = 'INITIATED',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum SYSTEM_ENV {
  PRODUCTION = 'production',
  DEVELOPMENT = 'development',
  QA = 'qa',
  UAT = 'uat',
  LOCAL = 'local',
}

export enum PARTNER_GATEWAY_EVENTS {
  LOAN_APPLICATION_STATUS_CHANGE = 'LOAN_APPLICATION_STATUS_CHANGE',
  LOAN_STATUS_CHANGE = 'LOAN_STATUS_CHANGE',
  MANUAL_REPAYMENT_SUCCESSFUL_COLLECTION = 'MANUAL_REPAYMENT_SUCCESSFUL_COLLECTION',
  SPLIT_MANUAL_REPAYMENT_COLLECTION_REQUEST = 'SPLIT_MANUAL_REPAYMENT_COLLECTION_REQUEST',
  CUMULATIVE_MANUAL_REPAYMENT_COLLECTION_REQUEST = 'CUMULATIVE_MANUAL_REPAYMENT_COLLECTION_REQUEST',
  AUTOMATIC_REPAYMENT_SUCCESS_NOTIFICATION = 'AUTOMATIC_REPAYMENT_SUCCESS_NOTIFICATION',
  AUTOMATIC_REPAYMENT_FAILURE_NOTIFICATION = 'AUTOMATIC_REPAYMENT_FAILURE_NOTIFICATION',
  MANUAL_REPAYMENT_SUCCESS_NOTIFICATION = 'MANUAL_REPAYMENT_SUCCESS_NOTIFICATION',
  MANUAL_REPAYMENT_FAILURE_NOTIFICATION = 'MANUAL_REPAYMENT_FAILURE_NOTIFICATION',
  PERSIST_FAILED_EVENT = 'PERSIST_FAILED_EVENT',
}

export enum LOAN_APPLICATION_STATUS {
  CREATED = 'Created',
  REJECTED = 'Rejected',
}

export enum LOAN_STATUS {
  WRITTEN_OFF = 'Written-Off',
  CLOSED = 'Closed',
  OVERPAID = 'Overpaid',
}