export enum LOAN_APPLICATION_WORKFLOW_STEPS {
    PROPRIETOR_INFORMATION = 'Proprietor Information',
    BANK_ACCOUNT = 'Bank Account',
    PROPRIETORSHIP_COMPANY_INFORMATION = 'Proprietorship Company Information',
    FINANCIAL_DETAILS_FROM_PARTNER = 'Financial Details from Partner',
    FINANCIAL_BRE = 'Financial BRE',
    LOAN_DETAILS = 'Loan Details',
    KYC = 'KYC',
    PROPRIETOR_RESIDENTIAL_ADDRESS = 'Proprietor Residential Address',
    CREDIT_BUREAU = 'Credit Bureau',
    BUREAU_BRE = 'Bureau BRE',
    LOAN_APPROVAL = 'Loan Approval',
    SANCTION_DETAILS = 'Consolidated Sanction Letter',
    AGREEMENT_DETAILS = 'Loan Agreement',
    E_MANDATE = 'E-Mandate',
    CUSTOM_MANDATE = 'Custom Mandate',
    VIDEO_KYC = 'Custom KYC',
    LOAN_APPLICATION_DOCUMENT_UPLOAD = 'Loan Application Document Upload',
    LOAN_DISBURSAL = 'Loan Disbursal',
  }
  